### ISSUE TITLE
Running RE-PACRR on custom data

### ISSUE THREAD

**Issue by bedapudi6788** [JoaoLages/TREC_WebTrack#1]
Hi, I was able to run the repacrr code provided by @khui and now I am trying to run repacrr on some custom data and see the results. It would be very helpful if you can provide some instructions (or any advice) for the same. For example, I understand how to generate the similarty matrices using word vectors but what I fail to understand is the matrix structure itself. i.e: should I keep the query's and document's word ordering or should I use idf sorting etc. Thank you.

**Comment by andrewyates** [comment]
It's best to keep the query's and document's original word ordering so that words in phrases stay together.

**Comment by bedapudi6788** [comment]
Thanks for clearing that up. Can you also provide some pointers on how should I create the qrels file for custom queries and data.

**Comment by andrewyates** [comment]
Sure, [this page]http://trec.nist.gov/data/qrels_eng/) describe the qrels file format.

**Comment by bedapudi6788** [comment]
Thanks for the suggestions.

**Comment by JoaoLages** [comment]
Hi @bedapudi6788, sorry but for some reason I was not notified of this issue.
Can I still help you somehow? I got the code there to construct the matrices.
If you need, just ask me in here any question you have or mail me :)

**Comment by bedapudi6788** [comment]
Hi @JoaoLages, I wrote a script for constructing the matrices but as I am new to this it would be very helpful if you could share yours, so that I can compare mine with yours. Also, if you could provide some general steps for running RE-PACRR on custom data it would be very helpful.

**Comment by JLJirges** [comment]
Joao, Joao, Joao...
👏👏👏

Really kewl!
You are famous and wanted!
Little Genius ! :D ;)

Don't forget about the 'little people' when you are on top!

2017-12-15 6:37 GMT+01:00 Bedapudi Praneeth <notifications@github.com>:

**Comment by JoaoLages** [comment]
@bedapudi6788 sure thing!
For the matrices, if you go under `data/data_iterator.py`, I have a function called `build_sim_matrix`. It simply gets the cosine similarity of every term in the query with every term in the document.
`gensim.models.Word2Vec` provides the function for this. 

To run with your data, it's just a matter of your providing the config. In `configs/model/up_repacrr.yml` you have an example config on custom data. Notice that the paths are different from the other configs (that use the provided matrices). The scripts will load/save matrices from those paths.

Not only in there but under `config/data/adhoc_example.yml` you have an example of custom data. If you want to generate matrices to those folders previously configures, you need to provide the `embeddings_path` and the `corpus_folder`. This `corpus_folder` is where your texts are.

I would advice keeping in mind what I said and going through the `data/data_iterator/read_corpus` function. It's where I construct the dataset.

**Comment by bedapudi6788** [comment]
Hi @JoaoLages, I am going to try this out on custom data and will post here if I face any issues. Can I keep this issue open until then? Thanks.

**Comment by JoaoLages** [comment]
Sure, tell me if I can help. 
For non-TREC data you'll have to change the configurations, but it's totally possible.

**Comment by JoaoLages** [comment]
@bedapudi6788 I am going to close this issue.
I have released a new version of the code where you are now able to use a pretrained model on your custom data. Give it a try if you're still interested and don't hesitate to reach out to me if you need any help.

**Comment by bedapudi6788** [comment]
@JoaoLages Thanks. I finally got some time to play around with this and it works perfectly. Thanks for providing the pre-trained simmats.

**Comment by JoaoLages** [comment]
@bedapudi6788
 Nice! I have only provided the pre-trained model, the simmats are originally from @andrewyates :)
